task:
  name: sparse_recovery
  kwargs:
    N: 50
    s: 3
    Phi: normal # choose between : identity, fourier, normal, random
    d: 20
    tau: 1 # in [0,1]

model:
  type: transformer
  n_dims: 20
  d_model: 64
  nhead: 4
  num_layers: 2
  dim_feedforward: 128
  n_positions: 101

training:
  batch_size: 64
  learning_rate: 0.0001
  train_steps: 100000
  save_every_steps: 10000
  keep_every_steps: 100000
  print_every: 100000


out_dir: outputs/compressed_sensing
