task:
  name: matrix_factorization
  kwargs:
    N: 20
    n1: 20
    n2: 20
    rank: 3
    problem: matrix-completion   # or matrix-sensing
    tau: 0.3                     # [0,1] 
    seed: 42

model:
  type: transformer
  n_dims: 40
  d_model: 64
  nhead: 4
  num_layers: 2
  dim_feedforward: 128
  n_positions: 101

training:
  batch_size: 64
  learning_rate: 0.0001
  train_steps: 1000
  save_every_steps: 100
  keep_every_steps: 1000
  print_every: 100


#out_dir: outputs/matrix_factorization
